### ISSUE TITLE
840 would look better

### ISSUE THREAD

**Issue by maettig** [tomaes/primevis#1]
Numbers with a lot of divisors create very interesting pictures, e.g. 210, 420 or 840.

**Comment by tomaes** [comment]
Hello Thiemo! I've never seen this issue posted until today. Sorry about that. :) I missed adding the web workers back then. But I'm not touching this code again, so blah.

**Comment by maettig** [comment]
Uh, this was 6 years ago, even before I moved to Berlin. ;-)
